import { change } from "../db_script";

// Generated by `yarn db g drop_oneq_journal_prompt_tables`, then trimmed to
// scope: the generator also proposed index-naming churn on the sync-infra
// tables (files / push_devices / team_members / teams_app sync_delta indexes)
// caused by pre-existing drift between table files and migrations — that is
// NOT part of the OneQ drop and D16 forbids touching sync infra here, so those
// hunks were removed. Only the journal/prompt domain leaves the schema.
//
// Down path: orchid's change() auto-reverses — the full column/index defs
// below let `db down` recreate both tables and the column. Row DATA is not
// restored (irreversible data loss by design: the OneQ demo content).

change(async (db) => {
	await db.changeTable("users", (t) => ({
		journalReminderTimes: t.drop(
			t.array(t.time().default(t.sql`'{}'::time without time zone[]`)),
		),
	}));

	await db.dropTable(
		"journal_entries",
		(t) => ({
			id: t.varchar(26).primaryKey(),
			prompt: t.varchar(500).nullable(),
			promptId: t
				.varchar(26)
				.foreignKey("prompts", "id", {
					onUpdate: "RESTRICT",
					onDelete: "SET NULL",
				})
				.nullable(),
			content: t.text(),
			authorUserId: t.uuid().foreignKey("users", "id", {
				onUpdate: "RESTRICT",
				onDelete: "CASCADE",
			}),
			teamId: t
				.varchar(26)
				.foreignKey("teams_app", "id", {
					onUpdate: "RESTRICT",
					onDelete: "SET NULL",
				})
				.nullable(),
			deletedAt: t.timestamp().nullable(),
			createdAt: t.timestamp().default(t.sql`clock_timestamp()`),
			updatedAt: t.timestamp().default(t.sql`clock_timestamp()`),
		}),
		(t) => [
			t.index([
				{
					column: "authorUserId",
				},
				{
					column: "updatedAt",
					order: "DESC",
				},
			]),
			t.index(
				[
					{
						column: "teamId",
					},
					{
						column: "updatedAt",
						order: "DESC",
					},
					{
						column: "id",
						order: "DESC",
					},
				],
				{
					name: "journal_entries_sync_delta_idx",
				},
			),
		],
	);
});

change(async (db) => {
	await db.dropTable(
		"prompts",
		(t) => ({
			id: t.varchar(26).primaryKey(),
			text: t.varchar(500),
			category: t.varchar(100).nullable(),
			tags: t.array(t.varchar(255)).nullable(),
			deletedAt: t.timestamp().nullable(),
			createdAt: t.timestamp().default(t.sql`clock_timestamp()`),
			updatedAt: t.timestamp().default(t.sql`clock_timestamp()`).index({
				order: "DESC",
			}),
		}),
		(t) =>
			t.index(
				[
					{
						column: "updatedAt",
						order: "DESC",
					},
					{
						column: "id",
						order: "DESC",
					},
				],
				{
					name: "prompts_sync_delta_idx",
				},
			),
	);
});
