import { change } from "../db_script";

// Generated by `yarn db g yantra_harness_state_tables`, trimmed to scope: the
// generator again proposed the pre-existing index-naming drift on sync-infra
// tables (files/push_devices/team_members/teams_app) — same drift excluded
// from 0008; not part of H1. Only the four yantra_* harness tables are added.

change(async (db) => {
	await db.createTable("yantra_turns", (t) => ({
		id: t.string(26).primaryKey(),
		repo: t.string(),
		baseBranch: t.string(),
		issue: t.integer(),
		state: t.string(20),
		tier: t.string(10).nullable(),
		pr: t.integer().nullable(),
		startedAt: t.timestamp(),
		endedAt: t.timestamp().nullable(),
		createdAt: t.timestamp().default(t.sql`clock_timestamp()`),
		updatedAt: t.timestamp().default(t.sql`clock_timestamp()`),
	}));

	await db.createTable("yantra_telemetry", (t) => ({
		id: t.string(26).primaryKey(),
		run: t.string(26).unique(),
		turn: t.string(26),
		repo: t.string().default("krishna-404/yantra"),
		baseBranch: t.string().default("staging"),
		issue: t.integer().default(0),
		role: t.string(20),
		lane: t.string(40).default("claude-max"),
		model: t.string(100),
		promptVersion: t.integer().default(1),
		tier: t.string(10),
		taskType: t.string(40).default("unknown"),
		startedAt: t.timestamp(),
		endedAt: t.timestamp(),
		wallS: t.integer().default(0),
		outcome: t.string(40),
		pr: t.integer().default(0),
		merged: t.boolean().default(false),
		autoMerged: t.boolean().default(false),
		reverted: t.boolean().default(false),
		tokensEst: t.integer().default(0),
		costUsd: t.doublePrecision().default(0),
		createdAt: t.timestamp().default(t.sql`clock_timestamp()`),
		updatedAt: t.timestamp().default(t.sql`clock_timestamp()`),
	}));
});

change(async (db) => {
	await db.createTable("yantra_runs", (t) => ({
		id: t.string(26).primaryKey(),
		turnId: t
			.string(26)
			.foreignKey("yantra_turns", "id", {
				onUpdate: "RESTRICT",
				onDelete: "CASCADE",
			})
			.nullable(),
		role: t.string(20),
		model: t.string(100),
		outcome: t.string(40).nullable(),
		startedAt: t.timestamp(),
		endedAt: t.timestamp().nullable(),
		createdAt: t.timestamp().default(t.sql`clock_timestamp()`),
		updatedAt: t.timestamp().default(t.sql`clock_timestamp()`),
	}));
});

change(async (db) => {
	await db.createTable("yantra_verdicts", (t) => ({
		id: t.string(26).primaryKey(),
		runId: t
			.string(26)
			.foreignKey("yantra_runs", "id", {
				onUpdate: "RESTRICT",
				onDelete: "CASCADE",
			})
			.nullable(),
		pr: t.integer(),
		headSha: t.string(64),
		verdict: t.string(20),
		tierConfirmed: t.string(10).nullable(),
		raw: t.json().nullable(),
		createdAt: t.timestamp().default(t.sql`clock_timestamp()`),
		updatedAt: t.timestamp().default(t.sql`clock_timestamp()`),
	}));
});
